### PR TITLE
fix(modal): use correct teleport target

### PR DESCRIPTION
**Pull request by 0x0dr1y**
Hello again! 

It seems like that the injected `modelTarget` doesn't contain the expected ref. Please rethink / check before merging :)

### CODE REVIEW

**Comment by mtorromeo** [comment]
Interesting... I thought all refs were supposed to be automatically unwrapped inside templates.

I'll take a closer look at this, since using `modalsTarget.value` would require `modalsTarget` to always be a `ref` (which might be fine).

**Comment by mtorromeo** [comment]
Also, this is something I am pretty sure I tested and was working fine, but there might be some precondition that triggers this particular behavior.

**Comment by 0x0dr1y** [comment]
I think the auto unwrapping will be introduced in the next version of Vue. For me it didn‘t work without the additional unwrapping. I‘ll also do some more testing tomorrow

**Comment by mtorromeo** [comment]
Yes, I am aware of that upcoming change, but I was convinced that it was already automatic inside the template.
I may be remembering incorrectly.

**Comment by mtorromeo** [comment]
I double-checked and can confirm that it works as I remembered.

The ref does not need to be unwrapped and in fact if I use the proposed change and manually unwrap it, `modalsTarget.value` resolves to `undefined` (basically accessing a non-existing `HTMLElement.value` property), and it falls back to teleporting the modal to `body` instead.

You can see it working properly here: https://mtorromeo.github.io/vue-patternfly/#/modal

**Comment by mtorromeo** [comment]
Here's the docs about refs unwrapping and templates: https://v3.vuejs.org/guide/reactivity-fundamentals.html#ref-unwrapping

Relevant quote:
> When a ref is returned as a property on the render context (the object returned from setup()) and accessed in the template, it automatically shallow unwraps the inner value.

**Comment by 0x0dr1y** [comment]
Thank you very much for cross checking! Might to be related to my app than. I'll dig into this and close the PR since it's not an issue with vue-patternfly. Again, thanks!

**Pull request closed without merging**
