### PR TITLE
fix(modal): prevent click propagation 

### PR DESCRIPTION
**Pull request by 0x0dr1y**
Only allow "outsideClose" clicks directly on the backdrop and modal wrapper element, and don't stop clicks propagating from the modal. This allows for example to close pf-select dropdowns with clicks within the modal. Another example would be a modal with dynamic content which get's removed.

If you don't want to have that behavior, feel free to close this PR! (I've already adjusted it inside my app)

### CODE REVIEW

**Comment by mtorromeo** [comment]
> and don't stop clicks propagating from the modal

I'm a bit confused by this. Click events should be propagated already. It's not clear to me why you wouldn't be able to close a pf-select dropdown.

I'll have to give it a try

**Comment by 0x0dr1y** [comment]
> > and don't stop clicks propagating from the modal
> 
> I'm a bit confused by this. Click events should be propagated already. It's not clear to me why you wouldn't be able to close a pf-select dropdown.
> 
> I'll have to give it a try

Closing a dropdown is probably not the best example (super rare case caused by some custom stuff). A better example would be an component with a "destroy button" which get's unmounted after clicking the button. If you want to i can prepare a working example (codepen or whatsoever) later that day, so you don't need to spend time trying to reproduce this.

**Comment by mtorromeo** [comment]
Sure, that would be helpful, thanks

**Comment by 0x0dr1y** [comment]
Sorry, didn't had the time yet. Will try to squeeze it in this week (if not i'll do it at the weekend)

**Comment by 0x0dr1y** [comment]
Closing this for now as i just don't have time atm :( Sorry!

**Pull request closed without merging**
