### PR TITLE
fix(tooltip): adjust default trigger

### PR DESCRIPTION
**Pull request by 0x0dr1y**
There was a small typo for the default trigger which lead to a non working tooltip in case there is no trigger defined

### CODE REVIEW

**Comment by 0x0dr1y** [comment]
(not sure why github included all the other commits of the previous MR)

**Comment by mtorromeo** [comment]
> (not sure why github included all the other commits of the previous MR)

I squashed the commits into a single one since the MR represented a single change. You should rebase this on master.

**Comment by mtorromeo** [comment]
I just squashed this one also, which results in the same equivalent commit. Just make sure to start from a clean master checkout if you want to merge any more changes.

BTW, thanks for the fixes!

**Comment by 0x0dr1y** [comment]
@mtorromeo sorry, i just saw your message. Do you mind creating a new release with the two bugfixes? :)

**Comment by mtorromeo** [comment]
Sure, I didn't have time before. I'll do a release later today or tomorrow.

**Comment by mtorromeo** [comment]
Fixes published in v0.2.1

**Pull request merged**
