### PR TITLE
Add few components

### PR DESCRIPTION
**Pull request by pebri86**
I added few components missing e.g modal and listview

### CODE REVIEW

**Comment by mtorromeo** [comment]
Thanks for the contribution. The new implementations are very welcome!

I have yet to test these new components but please don't add /dist to the repo. It was explicitly ignored for a reason.

Can you refactor the code adding only the new components?

**Comment by pebri86** [comment]
Thanks for your response, i've use patternfly for some of my enterprise project, i switch to vue recently and only found patternfly support for vue from your repo. 

that dist/ folder just to automate install anyway since i don't have access to npm repo so i directly install from my github repo fork. i've add it again in gitignore

**Comment by mtorromeo** [comment]
The removal of /dist and gitignore changes ended up adding even more commits so I just included the components manually which also needed some fixes and are still missing some features but they make up for a good start.

I skipped the Confirmation dialog since it's basically copy-paste of Modal. Once I add a couple of customization options to the Modal itself you won't need a dedicated confirmation component.

Thanks!

**Comment by pebri86** [comment]
Great solution and cleaner code, i still pretty new in vue so still discovering anything. Thanks

**Pull request closed without merging**
